config/routes.rb
Rails.application.routes.draw do
  get 'pages/about_us'
  get 'pages/courses'
  get 'pages/locations'
  get 'pages/contact_us'
  get 'pages/home'

  get 'home' => 'pages#home'
  get 'contact_us' => 'pages#contact_us'
  get 'locations' => 'pages#locations'
  get 'courses' => 'pages#courses'
  get 'about_us' => 'pages#about_us'

  root to: 'pages#home'

  match '*path' => redirect('/'), via: :get

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def courses
  end

  def locations
  end

  def contact_us
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_menu.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Week5</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path  %></li>
        <li><%= link_to 'Courses', pages_courses_path  %></li>
        <li><%= link_to 'Locations', pages_locations_path  %></li>
        <li><%= link_to 'About Us', pages_about_us_path  %></li>
        <li><%= link_to 'Contact Us', pages_contact_us_path  %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) + ' | ': '' %> Griffith College</title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>

<%= render partial: 'layouts/menu' %>

<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div><!--/row-->

  <footer>
    <p>&copy; Company 2015</p>
  </footer>

</div> <!-- /container -->

</body>
</html>

app/views/pages/about_us.html.erb
<% content_for :title, 'About Us' %>

There's nothing about us.

app/views/pages/contact_us.html.erb
<% content_for :title, 'Contact Us' %>

<form>
  <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" placeholder="Enter Name">
  </div>
  <div class="form-group">
    <label for="email">Email</label>
    <input type="email" class="form-control" id="email" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="content">Content</label>
    <textarea class="form-control" id="" content="" rows="3"></textarea>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

app/views/pages/courses.html.erb
<% content_for :title, 'Courses' %>

<h2>Courses</h2>
<ul>
  <li>Game Design</li>
  <li>Web Frameworks</li>
  <li>HUI / GUI</li>
  <li>...</li>
</ul>

app/views/pages/home.html.erb
<% content_for :title, 'Home' %>

<%= image_tag('GCD.jpg', style: 'width: 127px; height: 127px;') %>

Come to Griffith !

app/views/pages/locations.html.erb
<% content_for :title, 'Location' %>

Somewhere near a river.